//apply plugin: 'org.jetbrains.compose'

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion = 35
    buildToolsVersion = "35.0.0"
    
    packagingOptions {
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'

        // Optional, try excluding the resource file
        // exclude 'res/xml/msdk_network_security_config.xml'
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}
repositories {
    jcenter()
    maven {
        url 'https://maven.google.com/'
        name 'Google'
    }
    flatDir {
        dirs 'libs/android'
    }
    /*
    maven {
        url = uri("https://maven.pkg.github.com/pcamilojunior/mobile-sdk-android")
        credentials {
            username = "pcamilojunior"
            password = "ANDROID_ZOOM_SDK_PASSWORD"
        }
    }
    */
    maven {
        url = uri("https://maven.pkg.github.com/Jacksun84/mobile-sdk-android")
        credentials {
            username = "Jacksun84"
            password = "ANDROID_ZOOM_SDK_PASSWORD"
        }
    }
}

/** gradle.projectsEvaluated {
    def gradlePropertiesFile = rootProject.file('gradle.properties')
    if (gradlePropertiesFile.exists()) {
        def gradleProperties = new Properties()
        gradleProperties.load(new FileInputStream(gradlePropertiesFile))
        def hasChanged = false
        if (gradleProperties['android.enableJetifier'] != 'true') {
            gradleProperties['android.enableJetifier'] = 'true'
            hasChanged = true
        }
        if (hasChanged) {
            gradleProperties.store(gradlePropertiesFile.newWriter(), 'Updated by build-extras.gradle')
        }
    } else {
        gradlePropertiesFile.text = "android.useAndroidX=true\nandroid.enableJetifier=true"
    }
}**/

dependencies {
    implementation 'com.jacksun:zoom-sdk-android:7.1.6.41900'
    
    //implementation 'com.jacksun:zoom-sdk-android:6.3.10.27979'
    implementation 'com.google.android.flexbox:flexbox:3.0.0'
    implementation 'androidx.security:security-crypto:1.1.0-alpha05'
    implementation 'com.google.crypto.tink:tink-android:1.7.0'
    implementation 'com.google.android.exoplayer:exoplayer-core:2.17.1'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.17.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.appcompat:appcompat-resources:1.6.1'
    implementation 'androidx.databinding:viewbinding:7.1.2'
    
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.github.bumptech.glide:annotations:4.11.0'
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    implementation 'androidx.compose.material3:material3-window-size-class:1.5.0-alpha07'
    implementation 'androidx.compose.material3:material3:1.5.0-alpha07'

    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'com.airbnb.android:lottie:4.0.0'
    implementation 'androidx.webkit:webkit:1.9.0'
    implementation 'androidx.window:window:1.1.0'
    implementation 'androidx.window:window-java:1.1.0'

    // start 
    // probably we can remove these ones since they are from _internal-unified-test-platform-android-test-plugin-host-retention 
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.23'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.23'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.23'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-common:1.9.23'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.9.0'
    implementation 'org.jetbrains:annotations:23.0.0'
    // end

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.9.0'

    implementation 'androidx.core:core-ktx:1.8.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.9.1'

    implementation 'androidx.fragment:fragment-ktx:1.4.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.9.1'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'

    /* Ensure the application does not crash when users choose background effects. */
    implementation 'androidx.lifecycle:lifecycle-runtime-compose:2.9.4'
    implementation 'androidx.navigation:navigation-compose:2.9.2'
    implementation 'androidx.activity:activity-ktx:1.11.10'
    implementation 'androidx.annotation:annotation-experimental:1.1.0'
    implementation 'androidx.compose.foundation:foundation:1.9.4'
    implementation 'androidx.compose.foundation:foundation-layout:1.9.4'
    implementation 'androidx.compose.runtime:runtime:1.9.4'
    implementation 'androidx.compose.ui:ui:1.9.4'
    implementation 'androidx.compose.ui:ui-tooling-preview:1.9.4'
    implementation 'androidx.compose.material:material:1.9.4'
    implementation 'androidx.activity:activity-compose:1.11.0'
    implementation 'io.coil-kt:coil-compose:2.3.0'

    implementation(name:'commonlib', ext:'aar')
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
